#!/bin/bash

if [ "$1" == "" ]
then
echo "NO has puesto una IP valida para escanear"
echo "Sintaxis: ./miprimerscript.sh xxx.xxx.x" 
echo "Reemplaza las Equis con la ip a escanear"

else
for ip in `seq 1 254`; do
ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":"&
done
fi
